[package]
name = "meshcore-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive", "wrap_help"] }
tokio = "1.49.0"
log = "0.4.29"
log4rs = "1.4.0"

libmeshcore-client-support = { path = "../libmeshcore-client-support" }
