[package]
name = "libmeshcore-proto"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = "1.49.0"
log = { version = "0.4.29", features = ["kv", "serde"] }

[dev-dependencies]
log4rs = "1.4.0"

